### ISSUE TITLE
DataBase work

### ISSUE THREAD

**Issue by rexdivakar** [rexdivakar/Gateway#4]
Create a new table named "Session Manager"

1. "Session ID"
2. "User_name" foreign key -- from accounts detail
3. "Last Active" timestamp
4. "Session Duration" timestamp
5. "Token ID" primary key from accounts foreign key

make sure to link these tables with account_details, auto insert and create it when accessed.

**Comment by kalaimatheik** [comment]
Tried triggers, finding issue: working one it. feel link it should be done through code only. not. sure.

insert into account_details(Username,Password,PIN,Token ) values ('User','852',2588,'5555');
  
   CREATE TRIGGER Auto_updates 
   AFTER insert on account_details 
   BEGIN
	   
    UPDATE Session_ID SET Token_ID = select token from account_details 
   END;
  
  CREATE TRIGGER Auto_updates 
   AFTER update of account_details on account_details.Token
   BEGIN
    INSERT INTO Session_ID ( Username,Last_Active,Session_Duration,Token_ID)      
    VALUES
    (account_details.Username,datetime(),datetime(),account_details.Token.Token);
   END;
